artifacts_root: artifacts_test

data_ingestion:
  root_dir: artifacts_test/data_ingestion
  train_img_dir: artifacts_test/data_ingestion/train/img
  train_mask_dir: artifacts_test/data_ingestion/train/mask
  test_img_dir: artifacts_test/data_ingestion/test/img
  test_mask_dir: artifacts_test/data_ingestion/test/mask
  val_img_dir: artifacts_test/data_ingestion/val/img
  val_mask_dir: artifacts_test/data_ingestion/val/mask

  others_img_dir: artifacts_test/data_ingestion/others/img
  database_name: 'images_db'
  collection_name: 'images_dataset_collection'

data_validation:
  root_dir: artifacts_test/data_validation
  data_dir: artifacts_test/data_ingestion
  STATUS_FILE: artifacts_test/data_validation/status.txt

data_transformation:  
  data_dir: artifacts_test/data_ingestion
  batch_size: 16
  shuffle: False

model_trainer:
  root_dir: artifacts_test/model_trainer
  model_name: model.pth

model_evaluation:
  root_dir: artifacts_test/model_evaluation
  model_path: artifacts_test/model_trainer/model.pth

  